name: Run unit tests when code pushed to repository
on:
  push:
    branches:
      - '*'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: "24"
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Install dependencies
        run: npm install  # I wish package-lock.json was in git, cos then it would be "npm ci"

      - name: Run unit tests
        run: npm test

